# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nsFZOV-4pIqVcIWqYzlAQciNbleE8V8a
"""

import streamlit as st

# ---------- Page Config ----------
st.set_page_config(
    page_title="BMT",
    page_icon="",
    layout="centered"
)

# ---------- Hide Streamlit Footer ----------
hide_streamlit_style = """
<style>
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}
</style>
"""
st.markdown(hide_streamlit_style, unsafe_allow_html=True)

# ---------- App Header ----------
st.markdown("<h1 style='text-align: center;'>BMT</h1>", unsafe_allow_html=True)
st.markdown(
    "<p style='text-align: center;'>AI Chat & AI Video Generator</p>",
    unsafe_allow_html=True
)

st.markdown("---")

# ---------- Tabs ----------
tab1, tab2 = st.tabs([" Chat", " AI Video"])

# ---------- CHAT TAB ----------
with tab1:
    st.subheader("BMT AI Chat")

    user_input = st.text_input("မေးချင်တာရေးပါ (Myanmar / English)")

    if st.button("Send"):
        if user_input.strip() == "":
            st.warning("စာရေးပါ")
        else:
            # Temporary reply (AI မချိတ်သေး)
            st.success("BMT AI")
            st.write(f"မင်းရေးတာ  {user_input}")

# ---------- VIDEO TAB ----------
with tab2:
    st.subheader("AI Video Generator")

    script = st.text_area(
        "ဇာတ်ညွန်းရေးပါ (Myanmar / English)",
        height=150
    )

    language = st.selectbox(
        "ဘာသာစကား",
        ["Myanmar", "English"]
    )

    if st.button("Generate Video"):
        if script.strip() == "":
            st.warning("ဇာတ်ညွန်းရေးပါ")
        else:
            st.info("AI Video မကြာမီ ထည့်မယ် ")
            st.write("Script:", script)
            st.write("Language:", language)
